import type { Metadata } from "next";
import { Outfit, Ovo, Lora } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const outfit = Outfit({
  subsets: ["latin"], weight: ["400", "500", "600", "700"],
//   variable: "--font-outfit",
});

const ovo = Ovo({
  subsets: ["latin"], weight: ["400"], 
//   variable: "--font-ovo",
});


const lora = Lora({
  subsets: ["latin"], weight: ["400", "500", "600", "700"],
//   variable: "--font-outfit",
});


export const metadata: Metadata = {
  title: "Quinn's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.className} ${outfit.className} ${ovo.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
